### PR TITLE
Implementation of device manager in the BLE code to support pairing and authentication (required for use with Windows BLE hosts)

### PR DESCRIPTION
**Pull request by theseankelly**
I've tested this with windows phone, windows 10, and iPhone. I don't have access to an android phone.

### CODE REVIEW

**Comment by ataffanel** [comment]
Thanks!

You have added 2 headers from Nordic. Did you modify them? if not please use the version from the Nordic folder (the one we download). If they have been modified we have to find a solution.

So far we have managed to keep our open code in this repos, and we download the Nordic code for compiling-in the bluetooth support. I would like to keep it this way.

**Comment by theseankelly** [comment]
The two headers from Nordic are used to configure the pstorage and device manager modules in the softdevice. Look through the samples in the Nordic SDK download -- you'll see there's one of these for just about every sample (unless the sample doesn't implement pairing) and they don't appear as default headers in the SDK's include directory. 

I did copy the files from one of the samples (unmodified) but it seems weird to add one of the sample apps to the CF include path, and decided to just make versions specific to the CF. Thoughts?

**Comment by theseankelly** [comment]
Also, it looks like the continuous build check failed. Weird -- I'll look in to that. It's in one of the Nordic files so I really hope it isn't that pstorage.c isn't C99 compliant...

**Comment by ataffanel** [comment]
The header are in the zip we download but I agree that using one of the example does not sound very clean. Those header seems obvious so I do not think they are a big problem anyway ([Aparently the FSF agree](http://programmers.stackexchange.com/questions/216471/how-does-copyrights-apply-to-source-code-header-files)). I think it will be good enough to keep them as they are now but in a separate folder. The best I think is to create ```s110/Include``` so we keep all Nordic files in the s110 folder.

As for C99 the problem is just that we do not compile in C99 more (which is surprising I usually set the projects in C11 or gnu11). This fixes the problem for me:
``` diff
diff --git a/Makefile b/Makefile
index 8231ab6..39e2870 100644
--- a/Makefile
+++ b/Makefile
@@ -28,7 +28,7 @@ NRF_S110 ?= s110
 INCLUDES= -I Include -I Include/gcc -Iinterface
 
 CONFIG = -DRSSI_ACK_PACKET
-BUILD_OPTION = -g3 -O0 -Wall -fsingle-precision-constant -ffast-math
+BUILD_OPTION = -g3 -O0 -Wall -fsingle-precision-constant -ffast-math -std=gnu11
 PERSONAL_DEFINES ?=
 
 PROCESSOR = -mcpu=cortex-m0 -mthumb
```
I am curious of what compiler you are using if you did not see the problem. I am using ```arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20150529``` and I saw the build error.

**Comment by theseankelly** [comment]
I'm using arm-none-eabi-gcc through the arm-for-windows toolchain, version 5.2 2015q4.

Pull request updated with requested feedback - created s110/Include and put the two config headers there. Updated the makefile accordingly, and added the std=gnu11 flag.

**Comment by ataffanel** [comment]
Thank you!

There was a last problem that I fixed myself and ammended to your commit, I hope you don't mind, I did not want it to be pushed in any way unmodified.

The bonding code is writing bonding info in the flash but the default config made it write in the boorloader region (see https://github.com/bitcraze/crazyflie2-nrf-firmware/blob/master/readme.md#architecture). By luck it was in an empty region of the bootloader. I changed it to write just before the bootloader. The bootloader is not write protected so we have to be a bit careful there (it is still possible to recover it, but it will be much harder).

Anyway, it works and I merged it with my small change.

**Comment by theseankelly** [comment]
Yikes, that would have been a nasty bug. Thanks for checking. I didn't even think about WHERE the pstorage module would be writing info too...sorry for the oversight.

**Pull request closed without merging**
